import Head from 'next/head'
import { useState } from 'react';
import Nav from '../src/components/nav';
import styles from '../styles/Home.module.css';

export default function Home() {

  const [textInfoWrite, settextInfoWrite] = useState("");

  function writeText(text) {
    var t = text.split('');
    let i = 0;
    let p = "";

    const inter = setInterval(() => {
      if (!t[i]) clearInterval(inter);
      else {
        p += t[i];
        i++;
        settextInfoWrite(p);
      }
    }, 100);
  }

  if (textInfoWrite == "") writeText("Site em desenvolvimento :)");

  return (
    <div className={styles.container}>
      <Head>
        <title>Lani Systems</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/lani-Icon.svg" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Exo" />
      </Head>

      <Nav />
      <main className='centerlize text-white' style={{ overflow: "hidden" }}>
        <h2>{textInfoWrite}</h2>

      </main>

      <footer className='text-center flex flex-col gap-2'>
        <div className='text-white'>
          Lani Systems |  CNPJ: 46.006.437/0001-33 |  Telefones: (11) 95788-6697 | (11) 98852-0205
        </div>
      </footer>
    </div>
  )
}
